(lang dune 3.23)

(name pulse)

(generate_opam_files true)

(source
 (github Ender06-1/Pulse))

(authors "Ender06-1 <ndxendernight@gmail.com>")

(license MIT)

(package
 (name pulse)
 (synopsis "A simple programming language")
 (description "A simple programming language")
 (depends ocaml)
 (tags
  ("programming" "language")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
